
import React, { useState, useEffect } from 'react';
import { LandListing } from '../types';
import { addExpirationDates, ContractType, CONTRACT_LABELS } from '../utils/imageExpiration';

interface LandFormProps {
  onSubmit: (data: any) => void;
  onCancel: () => void;
  initialData?: LandListing | null;
}

// Importante: Definir InputField FORA do componente LandForm
// para manter a identidade do componente entre renders e não perder o foco a cada tecla digitada
const InputField: React.FC<{
  name: string;
  label: string;
  value: string;
  required?: boolean;
  placeholder?: string;
  autoFocus?: boolean;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
}> = ({ name, label, value, required = false, placeholder, autoFocus, onChange }) => (
  <div>
    <label htmlFor={name} className="block text-sm font-medium text-slate-700 mb-1">{label}</label>
    <input
      type="text"
      id={name}
      name={name}
      value={value}
      required={required}
      placeholder={placeholder}
      autoFocus={autoFocus}
      onChange={onChange}
      className="w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500"
    />
  </div>
);

const LandForm: React.FC<LandFormProps> = ({ onSubmit, onCancel, initialData }) => {
  const [formData, setFormData] = useState({
    title: '',
    location: '',
    fullAddress: '',
    price: '',
    tags: '',
    features: '',
    description: '',
    area: '',
    solarPosition: '',
    propertyType: '',
    images: '',
    code: '',
  });

  const [uploadedImages, setUploadedImages] = useState<string[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const [showCamera, setShowCamera] = useState(false);
  const [contractType, setContractType] = useState<ContractType>('1-year');
  const [isSaving, setIsSaving] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>('');

  useEffect(() => {
    if (initialData) {
      setFormData({
        title: initialData.title,
        location: initialData.location,
        fullAddress: initialData.fullAddress,
        price: initialData.price,
        tags: initialData.tags.join(', '),
        features: initialData.features.join(', '),
        description: initialData.description,
        area: initialData.area,
        solarPosition: initialData.solarPosition,
        propertyType: initialData.propertyType,
        images: initialData.images.join(', '),
        code: initialData.code,
      });
      setUploadedImages(initialData.images);
      setAutoGeneratedCode(initialData.code);
    } else {
      // Gerar código automático para novos anúncios
      const newCode = `IMV-${Date.now().toString().slice(-6)}`;
      setAutoGeneratedCode(newCode);
      setFormData(prev => ({ ...prev, code: newCode }));
    }
  }, [initialData]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;

    setIsUploading(true);
    const newImages: string[] = [];

    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      
      // Validar tipo de arquivo
      if (!file.type.startsWith('image/')) {
        alert(`O arquivo ${file.name} não é uma imagem válida.`);
        continue;
      }

      // Validar tamanho (máximo 2MB por imagem)
      if (file.size > 2 * 1024 * 1024) {
        alert(`A imagem ${file.name} é muito grande. Tamanho máximo: 2MB`);
        continue;
      }

      try {
        const base64 = await convertToBase64(file);
        newImages.push(base64 as string);
      } catch (error) {
        console.error('Erro ao converter imagem:', error);
        alert(`Erro ao processar a imagem ${file.name}`);
      }
    }

    setUploadedImages(prev => [...prev, ...newImages]);
    setIsUploading(false);
  };

  const convertToBase64 = (file: File): Promise<string | ArrayBuffer | null> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve(reader.result);
      reader.onerror = error => reject(error);
    });
  };

  const removeImage = (index: number) => {
    setUploadedImages(prev => prev.filter((_, i) => i !== index));
  };

  const handleCameraCapture = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    
    await handleImageUpload(e);
    setShowCamera(false);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Combinar imagens uploadadas com URLs (se houver)
    const urlImages = formData.images.split(',').map(s => s.trim()).filter(Boolean);
    const allImages = [...uploadedImages, ...urlImages];
    
    if (allImages.length === 0) {
      alert('Por favor, adicione pelo menos uma imagem.');
      return;
    }

    // Indicar que está salvando
    setIsSaving(true);

    // Simular um pequeno delay para dar feedback visual
    setTimeout(() => {
      let processedData = {
        ...formData,
        code: autoGeneratedCode, // Usar o código automático
        tags: formData.tags.split(',').map(s => s.trim()).filter(Boolean),
        features: formData.features.split(',').map(s => s.trim()).filter(Boolean),
        images: allImages,
        imageUrl: allImages[0] || '', // backward compatibility
      };

      // Adicionar datas de criação e expiração apenas para novos anúncios
      if (!initialData) {
        processedData = addExpirationDates(processedData, contractType) as any;
      }

      if (initialData) {
          onSubmit({ 
            ...processedData, 
            id: initialData.id, 
            createdAt: initialData.createdAt, 
            expiresAt: initialData.expiresAt,
            contractType: initialData.contractType 
          });
      } else {
          onSubmit(processedData);
      }
      
      setIsSaving(false);
    }, 500);
  };
  
  // (removido) Listener de propagação — não é necessário com onChange direto

  return (
    <main className="bg-white py-12">
      <div className="container mx-auto px-6 max-w-4xl">
        <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-6">
          {initialData ? 'Editar Terreno' : 'Adicionar Novo Terreno'}
        </h1>
        <form onSubmit={handleSubmit} className="space-y-6 bg-slate-50 p-8 rounded-xl shadow-lg">
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <InputField name="title" label="Título do Anúncio" value={formData.title} required autoFocus onChange={handleChange} />
            
            {/* Código Automático - Não Editável */}
            <div>
              <label htmlFor="code" className="block text-sm font-medium text-slate-700 mb-1">
                Código do Imóvel
                <span className="ml-2 text-xs text-emerald-600 font-semibold">✨ Gerado automaticamente</span>
              </label>
              <div className="relative">
                <input
                  type="text"
                  id="code"
                  name="code"
                  value={autoGeneratedCode}
                  disabled
                  className="w-full px-3 py-2 border-2 border-emerald-200 bg-emerald-50 rounded-md shadow-sm text-slate-700 font-mono font-bold cursor-not-allowed"
                />
                <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
                  <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
              </div>
              <p className="text-xs text-slate-500 mt-1">
                {initialData ? 'Este é o código original do imóvel' : 'Este código será usado para identificar o imóvel'}
              </p>
            </div>
          </div>

          <InputField name="price" label="Preço" value={formData.price} required placeholder="Ex: R$ 120.000" onChange={handleChange} />
          <InputField name="location" label="Localização (Cidade/Estado)" value={formData.location} required placeholder="Ex: Alter do Chão/PA" onChange={handleChange} />
          <InputField name="fullAddress" label="Endereço Completo" value={formData.fullAddress} required placeholder="Ex: Rua das Flores, 123, Bairro, Cidade - UF, CEP" onChange={handleChange} />
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <InputField name="area" label="Área Total" value={formData.area} required placeholder="Ex: 500m²" onChange={handleChange} />
            <InputField name="solarPosition" label="Posição Solar" value={formData.solarPosition} required placeholder="Ex: Nascente" onChange={handleChange} />
            <InputField name="propertyType" label="Tipo de Imóvel" value={formData.propertyType} required placeholder="Ex: Lote/Terreno" onChange={handleChange} />
          </div>

          <div>
            <label htmlFor="description" className="block text-sm font-medium text-slate-700 mb-1">Descrição</label>
            <textarea
              id="description"
              name="description"
              value={formData.description}
              onChange={handleChange}
              rows={5}
              required
              className="w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500"
            ></textarea>
          </div>

          <InputField name="features" label="Características (separadas por vírgula)" value={formData.features} required placeholder="Ex: Plano, Murado, Pronto para construir" onChange={handleChange} />
          <InputField name="tags" label="Tags (separadas por vírgula)" value={formData.tags} required placeholder="Ex: Investimento, Perto da praia" onChange={handleChange} />
          
          {/* Seção de Upload de Imagens */}
          <div className="border-2 border-dashed border-slate-300 rounded-lg p-6 bg-white">
            <label className="block text-sm font-medium text-slate-700 mb-2">
              Imagens do Terreno
            </label>
            <p className="text-xs text-slate-500 mb-4">
              Faça upload de imagens ou tire fotos (máximo 2MB por imagem, formatos: JPG, PNG, WebP)
            </p>
            
            <div className="flex flex-col sm:flex-row gap-3 mb-4">
              {/* Botão de Upload */}
              <label className="flex-1 cursor-pointer">
                <div className="flex items-center justify-center px-4 py-3 bg-emerald-50 text-emerald-700 rounded-lg border-2 border-emerald-200 hover:bg-emerald-100 transition-colors">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  <span className="font-semibold text-sm">Escolher Arquivos</span>
                </div>
                <input
                  type="file"
                  accept="image/*"
                  multiple
                  onChange={handleImageUpload}
                  disabled={isUploading}
                  className="hidden"
                />
              </label>

              {/* Botão de Câmera */}
              <label className="flex-1 cursor-pointer">
                <div className="flex items-center justify-center px-4 py-3 bg-blue-50 text-blue-700 rounded-lg border-2 border-blue-200 hover:bg-blue-100 transition-colors">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                  <span className="font-semibold text-sm">Tirar Foto</span>
                </div>
                <input
                  type="file"
                  accept="image/*"
                  capture="environment"
                  onChange={handleCameraCapture}
                  disabled={isUploading}
                  className="hidden"
                />
              </label>
            </div>
            
            {isUploading && (
              <div className="flex items-center justify-center py-4">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-600"></div>
                <p className="text-sm text-emerald-600 ml-3">Processando imagens...</p>
              </div>
            )}

            {/* Preview das imagens */}
            {uploadedImages.length > 0 && (
              <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-4">
                {uploadedImages.map((img, index) => (
                  <div key={index} className="relative group">
                    <img 
                      src={img} 
                      alt={`Preview ${index + 1}`}
                      className="w-full h-24 object-cover rounded-lg border-2 border-slate-200"
                    />
                    <button
                      type="button"
                      onClick={() => removeImage(index)}
                      className="absolute top-1 right-1 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-600"
                      aria-label="Remover imagem"
                    >
                      ×
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Campo opcional para URLs de imagens externas */}
          <div>
            <label htmlFor="images" className="block text-sm font-medium text-slate-700 mb-1">
              URLs de Imagens Externas (opcional, separadas por vírgula)
            </label>
            <input
              type="text"
              id="images"
              name="images"
              value={formData.images}
              onChange={handleChange}
              placeholder="https://exemplo.com/imagem1.jpg, https://exemplo.com/imagem2.jpg"
              className="w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500"
            />
            <p className="text-xs text-slate-500 mt-1">
              Se preferir, você também pode adicionar URLs de imagens hospedadas externamente
            </p>
          </div>

          {/* Configuração de Tipo de Contrato */}
          {!initialData && (
            <div className="bg-blue-50 border-2 border-blue-200 rounded-lg p-6">
              <div className="flex items-start">
                <svg className="w-6 h-6 text-blue-600 mr-3 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <div className="flex-1">
                  <h3 className="text-sm font-semibold text-blue-900 mb-2">
                    Tipo de Contrato
                  </h3>
                  <p className="text-xs text-blue-800 mb-4">
                    Selecione por quanto tempo este anúncio ficará disponível. Após o prazo, será removido automaticamente para liberar espaço de armazenamento.
                  </p>
                  <div className="space-y-3">
                    <label className="flex items-start p-3 bg-white rounded-lg border-2 border-blue-100 hover:border-blue-300 transition-colors cursor-pointer">
                      <input
                        type="radio"
                        name="contractType"
                        value="6-months"
                        checked={contractType === '6-months'}
                        onChange={() => setContractType('6-months')}
                        className="mt-1 mr-3"
                      />
                      <div>
                        <span className="text-sm font-semibold text-blue-900">{CONTRACT_LABELS['6-months']}</span>
                        <p className="text-xs text-blue-700 mt-1">Ideal para vendas rápidas ou promoções temporárias</p>
                      </div>
                    </label>
                    
                    <label className="flex items-start p-3 bg-white rounded-lg border-2 border-emerald-300 hover:border-emerald-400 transition-colors cursor-pointer">
                      <input
                        type="radio"
                        name="contractType"
                        value="1-year"
                        checked={contractType === '1-year'}
                        onChange={() => setContractType('1-year')}
                        className="mt-1 mr-3"
                      />
                      <div>
                        <span className="text-sm font-bold text-emerald-900">{CONTRACT_LABELS['1-year']} ✨ Recomendado</span>
                        <p className="text-xs text-emerald-700 mt-1">Equilíbrio perfeito entre tempo e gerenciamento de espaço</p>
                      </div>
                    </label>
                    
                    <label className="flex items-start p-3 bg-white rounded-lg border-2 border-purple-100 hover:border-purple-300 transition-colors cursor-pointer">
                      <input
                        type="radio"
                        name="contractType"
                        value="indefinite"
                        checked={contractType === 'indefinite'}
                        onChange={() => setContractType('indefinite')}
                        className="mt-1 mr-3"
                      />
                      <div>
                        <span className="text-sm font-semibold text-purple-900">{CONTRACT_LABELS['indefinite']}</span>
                        <p className="text-xs text-purple-700 mt-1">O anúncio permanecerá ativo até ser removido manualmente</p>
                      </div>
                    </label>
                  </div>
                  
                  <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-lg">
                    <p className="text-xs text-amber-800 flex items-start">
                      <svg className="w-4 h-4 mr-2 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <span><strong>Dica:</strong> Você receberá um aviso 30 dias antes do anúncio expirar e poderá renová-lo manualmente se desejar.</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="flex justify-end space-x-4 pt-4 border-t">
            <button
              type="button"
              onClick={onCancel}
              disabled={isSaving}
              className="bg-slate-200 text-slate-800 font-bold py-2 px-6 rounded-lg hover:bg-slate-300 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Cancelar
            </button>
            <button
              type="submit"
              disabled={isSaving}
              className="bg-emerald-500 text-white font-bold py-3 px-8 rounded-lg hover:bg-emerald-600 transition-colors shadow disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {isSaving ? (
                <>
                  <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  <span>Salvando...</span>
                </>
              ) : (
                <>
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  <span>Salvar Anúncio</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </main>
  );
};

export default LandForm;
